const TWITCH_CLIENT_ID = process.env.TWITCH_CLIENT_ID;
const TWITCH_PASSWORD = process.env.TWITCH_PASSWORD;
const TWITCH_USERNAME = process.env.TWITCH_USERNAME;
const TWITCH_CHAT_COLOR = process.env.TWITCH_CHAT_COLOR;
const TWITCH_SECRET = process.env.TWITCH_SECRET;

export { TWITCH_CLIENT_ID, TWITCH_PASSWORD, TWITCH_USERNAME, TWITCH_CHAT_COLOR, TWITCH_SECRET };
