const TWITCH_CLIENT_ID = process.env.TWITCH_CLIENT_ID;
const TWITCH_SECRET = process.env.TWITCH_SECRET;
const TWITCH_USERNAME = process.env.TWITCH_USERNAME;
const TWITCH_CHANNEL = process.env.TWITCH_CHANNEL;

export { TWITCH_CLIENT_ID, TWITCH_SECRET, TWITCH_USERNAME, TWITCH_CHANNEL };
